### ISSUE TITLE
Don't connect only to the first MX record

### ISSUE THREAD

**Issue by amaurym** [reacherhq/check-if-email-exists#1049]
After a MX DNS check, if we find multiple records, we only connect to the first one:

 https://github.com/reacherhq/check-if-email-exists/blob/9fd10c4ecdbbbcab845d4bc2689115812716507a/core/src/lib.rs#L169-L170

Some mail servers might add a simple protection to put a dummy MX record as the lowest one, e.g.;

```
9 | mx1.example.com // fake one
10 | real.mx.server.com
```

In this case, check-if-email-exists only connects to the 1st one.

Some proposals to solve thiss:
- traverse all records
- traverse in reverse order

**Comment by lechuhuuha** [comment]
> Some mail servers might add a simple protection to put a dummy MX record as the lowest one, e.g.; 
9 | mx1.example.com // fake one
10 | real.mx.server.com

- What do u mean by the lowest one when in example the 9th one is the fake one? Miss typo?
- Did traverse all records and traverse in reverse order will took too long if u have large amount of list email?

- And do you have any solution relate to Domain/MX Records Check. 
My only solution is now after call RCPT command if i get 550 error i call RSET and doing some IP rotation to avoid blacklist but that rn just like a temporary solution.
Any idea that you would like to share will be much appreciate!

**Comment by amaurym** [comment]
closed by #1070
