### ISSUE TITLE
function `check_single_email` is private

### ISSUE THREAD

**Issue by robsonfs** [reacherhq/check-if-email-exists#1089]
First of all, thanks a lot for this amazing crate. It does exactly what I was about to implement. I wonder if there are any good reasons to keep the function `check_single_email` private. I need something similar in my use case. Would it be helpful to submit a PR to make it public?

**Comment by amaurym** [comment]
You can simply call `check_email` with a single-item Vec.

**Comment by robsonfs** [comment]
Yes, I can do it. In fact, I'm already doing this. But I am implementing an API, and just for the sake of semantics, when the user goes to /validates_email?email=someone@gmail.com, I'd like to return a single instance of `CheckEmailOutput`, not an array of it, even though it is a one-element array.

**Comment by amaurym** [comment]
On the response, you can take the first (and only) item. It's done like so in Reacher's backend:

https://github.com/reacherhq/backend/blob/5385116f05523db3df479d5b90d024504f4d2a36/src/check.rs#L45

i'm still thinking if the `check_email` function should be 1-email or multiple-email. But in any case, i'd prefer to expose only that one `check_email` function.

**Comment by robsonfs** [comment]
Okay, @amaurym, I liked [this approach](https://github.com/reacherhq/backend/blob/5385116f05523db3df479d5b90d024504f4d2a36/src/check.rs#L45)
Thanks again!
