### ISSUE TITLE
MacOs binary is not ok for version 0.8.29

### ISSUE THREAD

**Issue by dhensen** [reacherhq/check-if-email-exists#1092]
The binary for macOs is not working (https://github.com/reacherhq/check-if-email-exists/releases/download/v0.8.29/check_if_email_exists-x86_64-apple-darwin.tar.gz)

I'm getting:
```
zsh: exec format error: ./check_if_email_exists
```

Note that the size of the tar is also off. It's just 115KB while the rest of them are in megabyte order of magnitude.

The  v0.8.28 binary is working for macOs though, so something might be off with your build process.

**Comment by random-element** [comment]
For 0.8.29: 
```bash
$file check_if_email_exists 
check_if_email_exists: data
```

For 0.8.28:
```bash
file check_if_email_exists
check_if_email_exists: Mach-O 64-bit executable x86_64
```

**Comment by amaurym** [comment]
I will mark this as wontfix. I just tried the newest v0.8.32 from the releases page, and it works on macOS.

If you want v0.8.29, please build it from source.
