### ISSUE TITLE
SmtpError Client host [44.202.40.57] blocked by RBL

### ISSUE THREAD

**Issue by jbspeakr** [reacherhq/check-if-email-exists#1110]
### Email Provider

mailbox.org

### What happened?

According to the docs `It might happen on rare occasions that the email provider doesn't allow real-time verification of emails. In this case, there's unfortunately nothing Reacher can do. Please let us know if this happens, we're working on finding ways to solve these issues, which in most occasions are solved on a case-by-case basis.`

Hence, I would like to let you know that there seems to be an issue when talking smtp with mailbox.org because one of your hosts seems to be on a spamhaus blocklist:

```
"smtp": {
    "error": {
      "type": "SmtpError",
      "message": "permanent: 5.7.1 Service unavailable; Client host [44.202.40.57] blocked by RBL; https://www.spamhaus.org/sbl/query/SBLCSS / https://www.spamhaus.org/query/ip/44.202.40.57"
    }
  }
```

**Comment by amaurym** [comment]
Hey, thanks @jbspeakr. It seems like a AWS ip address. Just to confirm, this was using https://api.reacher.email, right?

This means that the IP address got blacklisted. Just to want make sure if it was your server or my server.

**Comment by amaury1729** [comment]
Closing as stale.
