### ISSUE TITLE
io: socks5 error: i/o error: failed to lookup address information: Name does not resolve

### ISSUE THREAD

**Issue by kushagraagent47** [reacherhq/check-if-email-exists#1230]
### Email Provider

kushagraagent47@gmail.com

### What happened?

I am using AWS EC2 of instance
Input -

{
  "from_email": "hey@level.game",
  "to_email": "kushagra1@level.game",
  "proxy": {
    "host": "string",
    "port": 0
  }
}

### Relevant log output

```shell
{
    "input": "kushagra1@level.game",
    "is_reachable": "unknown",
    "misc": {
        "is_disposable": false,
        "is_role_account": false,
        "gravatar_url": null
    },
    "mx": {
        "accepts_mail": true,
        "records": [
            "aspmx3.googlemail.com.",
            "aspmx.l.google.com.",
            "alt1.aspmx.l.google.com.",
            "alt2.aspmx.l.google.com.",
            "aspmx2.googlemail.com."
        ]
    },
    "smtp": {
        "error": {
            "type": "SmtpError",
            "message": "io: socks5 error: i/o error: failed to lookup address information: Name does not resolve"
        }
    },
    "syntax": {
        "address": "kushagra1@level.game",
        "domain": "level.game",
        "is_valid_syntax": true,
        "username": "kushagra1",
        "normalized_email": "kushagra1@level.game",
        "suggestion": null
    }
}
```

**Comment by kushagraagent47** [comment]
If I remove it, It gets stuck in sending request
![Uploading Screenshot 2022-11-23 at 10.49.17 AM.png…]()

**Comment by kushagraagent47** [comment]
If I remove it, It gets stuck in sending request
![Screenshot 2022-11-23 at 10 49 17 AM](https://user-images.githubusercontent.com/34413025/203474042-b545fd12-5142-4622-83a0-ac322c3c2cd1.png)

**Comment by amaurym** [comment]
Yes, hanging is normal on AWS, because they block port 25 by default. You need to ask them to open. See the bottom of this page for more info  https://help.reacher.email/self-host-guide.

from_email is used for the MAIL FROM step in the smtp handshake. It's an optional field, and will default to user@example.org.
