### ISSUE TITLE
Getting 504 response when hosting container on digital ocean droplet

### ISSUE THREAD

**Issue by virgincodes** [reacherhq/check-if-email-exists#1254]
### What happened?

So deployed the container on a digital ocean droplet, I've been able to test the container on my local machine works like a charm, now moved the project to the digital ocean and it give me `504` which is similar to what happens when i try it out on my school wifi, am guessing this is a network issue any help?

### Relevant log output

```shell
| 172.18.0.6 - - [12/Jan/2023:01:41:00 +0000] "POST /v0/check_email HTTP/1.1" 504 167 "-" "axios/0.19.2" "-"
```

**Comment by virgincodes** [comment]
Update on this so i looked more at the response and here is what i see

For a request like this

```
{
    "email": "doesnt_exist@gsmail.com"
} 
```
I get this response 

```json
{
"input":"",
"is_reachable":"invalid"
,"misc": {"is_disposable":false,"is_role_account":false,"gravatar_url":null}
,"mx":{"accepts_mail":false,"records":[]},
"smtp":{"can_connect_smtp":false,"has_full_inbox":false,"is_catch_all":false,"is_deliverable":false,"is_disabled":false},"syntax":{"address":null,"domain":"","is_valid_syntax":false,"username":"","normalized_email":null,"suggestion":null
  }
}
```
This email obviously doesn't exist and any email i use has the exact same result , am so confused at the moment

**Comment by amaurym** [comment]
It's probably a network issue yeah, DO blocks port 25 by default AFAIK. Can you provide the full logs with `RUST_LOG=debug`?

**Comment by virgincodes** [comment]
So did a bit of research digital ocean doesn't let SMTP request if ur account is new so I just moved my image to Heroku and it worked simply enough, not ideal but am not a big service yet so my requirements aren't large
