### ISSUE TITLE
RCH_SMTP_TIMEOUT / smtp_timeout not respected?

### ISSUE THREAD

**Issue by tchwpkgorg** [reacherhq/check-if-email-exists#1320]
### Email Provider

WHM / Exim

### Version of check-if-email-exists (if running it yourself)

0.4.0

### What happened?

I have an Exim server (WHM) which responds to SMTP commands after 20-30 seconds:

```
# telnet 10.11.12.13 25
Trying 10.11.12.13...
Connected to 10.11.12.13.
Escape character is '^]'.

<----- here, this SMTP server waits for 20-30 secs before it replies ----->

220-test-server ESMTP Exim 4.96 #2 Fri, 02 Jun 2023 22:46:26 +0100 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
```

reacher_backend gives up earlier, after around 15 seconds - and marks email addresses as "unknown".

I've tried setting RCH_SMTP_TIMEOUT / smtp_timeout variables to 60, but reacher_backens seems to ignore it and still gives up after ~15 secs.

**Comment by mrbrown444** [comment]
Pls can I use this smtp to send bulk Email?

**Comment by amaury1729** [comment]
Opening again. Some other people are also asking for this, so I'll put it back.
