### ISSUE TITLE
Request doesn't fail with wrong syntax

### ISSUE THREAD

**Issue by zagoli** [reacherhq/check-if-email-exists#1326]
### Version of check-if-email-exists (if running it yourself)

latest

### What happened?

I send a request with the following wrong syntax:
`{ "to-email" : "example@gmail.com" }`. Note the wrong `to-email` instead of `to_email`.

I expect this request to fail with an http error. Instead the response is `200 OK` with the field `is_reachable` set to `invalid`.

**Comment by amaury1729** [comment]
`"to-email"` will simply be ignored, just like any other fields.

The questions here is if we omit `"to_email"`, or even if we manually put `"to_email": ""`, should it check the empty string, or should it fail early.

In the backend, I'm okay to fail early with a HTTP error. @zagoli would you like to create a PR?

**Comment by zagoli** [comment]
Ok I'll try to do it
