### ISSUE TITLE
Yahoo always fails

### ISSUE THREAD

**Issue by 0xlinus** [reacherhq/check-if-email-exists#1335]
### Email Provider

yahoo.com

### Version of check-if-email-exists (if running it yourself)

0.9 and Web

### What happened?

I've tried both, myself using the cli, and the web. It seems that yahoo verification is not working
![image](https://github.com/reacherhq/check-if-email-exists/assets/99757679/fb527d06-7afe-4392-9322-8092da49341a)

**Comment by amaury1729** [comment]
The bug was also documented in #1308, and has now been fixed.
