### ISSUE TITLE
Use either rustfmt.toml or .rustfmt.toml but not both

### ISSUE THREAD

**Issue by szabgab** [reacherhq/check-if-email-exists#1467]
It seem that in this repository there is both a `rustfmt.toml` and a `.rustfmt.toml` file which is confusing as only one will be used. [See this report](https://rust-digger.code-maven.com/news/rustfmt-stats)

**Comment by amaury1093** [comment]
Makes sense. Would you like to create a PR?

**Comment by szabgab** [comment]
no, thanks.

**Comment by mcamou** [comment]
Here's a PR: https://github.com/reacherhq/check-if-email-exists/pull/1524

**Comment by amaury1093** [comment]
Thanks @mcamou
