### ISSUE TITLE
socks5 error: Received malformed reply

### ISSUE THREAD

**Issue by almostkareem** [reacherhq/check-if-email-exists#1523]
### What happened?

"smtp": {
		"error": {
			"type": "SmtpError",
			"message": "io: socks5 error: Received malformed reply"
		}
	},

PS: I'm using OxyLabs socks proxy.

**Comment by EmreKaplaner** [comment]
I have the same issue, using SmartProxy SOCKS5.

**Comment by almostkareem** [comment]
> I have the same issue, using SmartProxy SOCKS5. This could be an issue on the proxy server's side, if port 25 is not open on their side.

Thanks bro, i figured that out myself after getting no response on this issue.

**Comment by EmreKaplaner** [comment]
> > I have the same issue, using SmartProxy SOCKS5. This could be an issue on the proxy server's side, if port 25 is not open on their side.
> 
> Thanks bro, i figured that out myself after getting no response on this issue.

Great, man! If you resolved it, may I also ask which proxy provider resolved this issue? I couldn't find one yet. It's probably also hard to find a proxy provider which has both clean IP's and also port 25 open.

**Comment by almostkareem** [comment]
I deployed my own socks docker containers in Contabo servers.
