### ISSUE TITLE
Misspelled Domain Detection

### ISSUE THREAD

**Issue by amaurym** [reacherhq/check-if-email-exists#318]
Some tools offer like: `someone@gmal.com` -> `Did you mean someone@gmail.com`. Would be nice to add it to this tool too.

**Comment by liamhtml** [comment]
this really wouldn't be too complicated to implement. you'd just want to create a list of common email domains and then compare it to the input. if it's close enough to one of the common domains ([based on the levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance)), send a correction.

**Comment by Agreon** [comment]
How would you like the resulting PR to output this information? Just passed in the `error` field` Or the similar provider just in a new field like `similar_mail_provider` that can be used by the different frontends?

**Comment by amaurym** [comment]
I propose the following algorithm:
```
// First, run the normal email verification code
res, err = check_email()

If err == MxError || err == SmtpError
  s := check_for_similar_provider()
  if s != nil {
    res.syntax.suggestion = <full correct email>
  }
```

Basically, only check for similar providers if we got an error on the mispelled domain. Then, put the correct full corrected email under `syntax.suggestion`.

Does this sound good to you?
