### ISSUE TITLE
How to check if yahoo emails are disabled or not

### ISSUE THREAD

**Issue by amaury1729** [reacherhq/check-if-email-exists#473]
We use the [Yahoo's API](https://github.com/amaurymartiny/check-if-email-exists/blob/master/core/src/smtp/yahoo.rs#L127) to check if Yahoo emails exist or not.

This checks if the email's username has already been used or not. But unfortunately, it doesn't check if the account is disabled. This leads to some hard bounces on disabled yahoo addresses.

We would need a clever way to solve this.

If you want to work on this, and need some disabled yahoo emails to test, I may have 1-2 to give you.

**Comment by miamitchi** [comment]
Hi Mr @amaury1729  did you find the solution how to check disabled account ?

**Comment by codemonies** [comment]
Also looking for a solution. Currently the only way seems to require sending an actual email. However, I see some services are able to verify whether an account is disabled without sending any emails. Any ideas how?

**Comment by miamitchi** [comment]
@codemonies Hi Mr can you geve example of this services?? , because i think this problem is integer in poleteque of yahoo

**Comment by codemonies** [comment]
> @codemonies Hi Mr can you geve example of this services?? , because i think this problem is integer in poleteque of yahoo

I still don't have a solution. The only way I have found so far is by actually sending an email.
