### ISSUE TITLE
Proxy authentication

### ISSUE THREAD

**Issue by roshanjonah** [reacherhq/check-if-email-exists#875]
I see the following flags being available...
--proxy-host
--proxy-port

But I need to be able to use authentication for our SOCKS5 proxy. Is there a way to add these to the script? Raising it as per #589

**Comment by amaurym** [comment]
That's not implemented right now, but it's pretty easy to add. Would you like to create a PR?

**Comment by roshanjonah** [comment]
I would totally do it if I had a little knowledge of rust :) Any chance you could work on it when you get a chance mate?

**Comment by amaurym** [comment]
Closed by https://github.com/reacherhq/backend/issues/194
