### ISSUE TITLE
Outdated async-smtp github URL

### ISSUE THREAD

**Issue by pawroman** [reacherhq/check-if-email-exists#888]
It seems that async-smtp was moved to a new URL: https://github.com/async-email/async-smtp 

The project's requirements still point a the old URL which should be updated:
https://github.com/reacherhq/check-if-email-exists/blob/387ce62aeb998de9f82724d2e09f510fc6bd043e/core/Cargo.toml#L20

**Comment by amaurym** [comment]
Yes. Pending on https://github.com/async-email/async-smtp/pull/36#issuecomment-799398484

**Comment by pawroman** [comment]
Oh, ok. Thanks for clarifying!

**Comment by amaurym** [comment]
This is fixed in 0.8.21.
