### ISSUE TITLE
client: Connection closed

### ISSUE THREAD

**Issue by Marwen94** [reacherhq/check-if-email-exists#889]
Hello,

I'm running into `client: Connection closed` error when verifying the SMTP deliverability on every mail that I try to validate. I don't think that my IP is blacklisted since I have a new EC2 instance. Here is an example of the responses I'm getting : 

`[
   {
      "input":"someone@hotmail.com",
      "is_reachable":"unknown",
      "misc":{
         "is_disposable":false,
         "is_role_account":false
      },
      "mx":{
         "accepts_mail":true,
         "records":[
            "hotmail-com.olc.protection.outlook.com."
         ]
      },
      "smtp":{
         "error":{
            "type":"SmtpError",
            "message":"client: Connection closed"
         }
      },
      "syntax":{
         "address":"someone@hotmail.com",
         "domain":"hotmail.com",
         "is_valid_syntax":true,
         "username":"someone"
      }
   }
]`

Do you know what might cause this behaviour ?

Thanks in advance.

**Comment by amaurym** [comment]
Hey @Marwen94! Yes, you need to file an application to aws to open port 25 on EC2: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/
