### ISSUE TITLE
Docker registry

### ISSUE THREAD

**Issue by cortopy** [reacherhq/check-if-email-exists#901]
This is just a tiny issue that confused me a bit today

The docker images are being published to the Docker registry https://hub.docker.com/r/amaurymartiny/check-if-email-exists. The README points to [reacherhq](https://hub.docker.com/r/reacherhq/backend) which has not been updated for some time.

Would it be possible to either have `amaurymartiny` as the official one or update `reacherhq`?

**Comment by amaurym** [comment]
Sorry about that, the latest version has been pushed to https://hub.docker.com/r/reacherhq/check-if-email-exists.
