### ISSUE TITLE
SMTP Connection closed on Aws ubuntu server  

### ISSUE THREAD

**Issue by kapilsingh421** [reacherhq/check-if-email-exists#902]
Hey,
SMTP Connection closed on Aws ubuntu server.
Maybe Aws is blocking port 25 as checked using Telnet (not able to connect)
But I am able to telnet on port 465...so how we can change SMTP to work on 465 so that we can get a response from the server successfully. (i am using docker image with the latest version)

"smtp":{"error":{"type":"SmtpError","message":"client: Connection closed"}},

**Comment by amaurym** [comment]
See https://github.com/reacherhq/check-if-email-exists/issues/889 and #877

**Comment by kapilsingh421** [comment]
Thanks it is working ...
