### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by neobgd** [reacherhq/check-if-email-exists#911]
Hello,
when I try to build from source on last step I got the error:

` Compiling check-if-email-exists-cli v0.8.22 (/home/ec2-user/check-if-email-exists/check-if-email-exists)
error: could not compile `check-if-email-exists-cli`.

Caused by:
  process didn't exit successfully: `rustc --crate-name check_if_email_exists --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=fca2f4d2e7a8f92b -C extra-filename=-fca2f4d2e7a8f92b --out-dir /home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps -L dependency=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps --extern check_if_email_exists=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libcheck_if_email_exists-cec050b7883b36e3.rlib --extern clap=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libclap-e8daf069634896b4.rlib --extern env_logger=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libenv_logger-630a272eced83a08.rlib --extern hyper=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libhyper-45e1636d4a5705f0.rlib --extern once_cell=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libonce_cell-20b5afef737fe3d7.rlib --extern serde=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libserde-ae09c83fbf83e157.rlib --extern serde_json=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libserde_json-23a96e5b65965fab.rlib --extern tokio=/home/ec2-user/check-if-email-exists/check-if-email-exists/target/release/deps/libtokio-f3c6a82d509030e5.rlib` (signal: 9, SIGKILL: kill)
`

**Comment by amaurym** [comment]
@neobgd Are you still seeing this error? I managed to build from source on windows, macOS and linux.

Closing for now.
