### ISSUE TITLE
Valid email address shown as invalid

### ISSUE THREAD

**Issue by dcormier** [reacherhq/check-if-email-exists#919]
`test+📧@gmail.com`

[Relevant RFC.](https://tools.ietf.org/html/rfc6531#section-3.3)

The [live demo](https://reacher.email/) shows this as having invalid syntax, but it doesn't (as long as the receiving SMTP server supports [the SMTPUTF8 extension](https://tools.ietf.org/html/rfc6531#section-3.2)).

```json
{
  "input": "test+📧@gmail.com",
  "is_reachable": "invalid",
  "misc": {
    "is_disposable": false,
    "is_role_account": false
  },
  "mx": {
    "accepts_mail": false,
    "records": []
  },
  "smtp": {
    "can_connect_smtp": false,
    "has_full_inbox": false,
    "is_catch_all": false,
    "is_deliverable": false,
    "is_disabled": false
  },
  "syntax": {
    "address": null,
    "domain": "",
    "is_valid_syntax": false,
    "username": ""
  }
}
```

**Comment by amaurym** [comment]
Yes, you're right! I'll close this in favor of https://github.com/reacherhq/check-if-email-exists/issues/893.
