### ISSUE TITLE
Email from icloud.com is not reachable

### ISSUE THREAD

**Issue by arquitecturatic** [reacherhq/check-if-email-exists#934]
Hi,
All emails from icloud.com are invalid.
![iclouderror](https://user-images.githubusercontent.com/86427310/123300901-aa4f0400-d4e0-11eb-80fb-0e7da94a2f18.jpg)
![zerobounce](https://user-images.githubusercontent.com/86427310/123300907-ab803100-d4e0-11eb-87a6-4370fbad5f8b.jpg)

Best regards.

**Comment by Ozussh** [comment]
Same results

**Comment by beshoo** [comment]
It is random, sometimes it works sometimes it not
