### ISSUE TITLE
Can check-if-email-exists behavior be classified as spam?

### ISSUE THREAD

**Issue by beshoo** [reacherhq/check-if-email-exists#967]
Hello,
Let's say I have 1M email address and I want to use "check-if-email-exists" to filter bad emails.
I set the correct **Helo** server and the correct from-email which match the **Helo** server domian.

* The forward DNS lookup (domain name to IP address) of my IP matches the HELO value set in my server
* Forward and rDNS are resolve in public DNS for both the IP and the HELO value.
* The HELO is a fully qualified domain name (FQDN).

So do you believe if I want to check 1M email, My server will be classified as spam?

**Comment by amaurym** [comment]
It really depends on the IP reputation of your server. See https://github.com/reacherhq/check-if-email-exists/issues/234 for ideas about IP blacklisting.
