### ISSUE TITLE
Ability to configure DNS nameservers

### ISSUE THREAD

**Issue by cortopy** [reacherhq/check-if-email-exists#977]
When querying for [mx records](https://github.com/reacherhq/check-if-email-exists/blob/master/core/src/mx.rs#L89) the default options for the resolver are used. This means that all users must use [Google's nameservers](https://docs.rs/async-std-resolver/0.20.3/async_std_resolver/config/struct.ResolverConfig.html#impl-Default).

I think this has important consequences:

- European users may be in very murky waters by using Google's nameservers as their compliance with GDPR is totally unclear. Recent court judgements in France show how difficult this can be. Other nameservers, like [Quad9](https://www.quad9.net/privacy/compliance-and-applicable-law/) are built with GDPR in mind and are a much better option
- The local machine `/etc/resolv.conf` is ignored altogether even though it may be carefully configured to comply with firewall rules, internal setups, etc.
- Google's nameservers may not be the fastest and users may want to use others

Considering this, I personally think that using the local machine configuration is a better option since users can then choose whichever nameserver they prefer. There is a `Resolver::from_system_conf` which could be used. 

Would a PR with this change be acceptable?

**Comment by amaurym** [comment]
Yes, thanks, this is a great point! Would definitely like to see a PR.

> The local machine /etc/resolv.conf

BTW, do you know how this works on Windows? My no1 priority is that this change should work out-of-the-box for users on all platforms.

**Comment by cortopy** [comment]
According to the docs, it will use the Windows registry. I'm not a Windows person myself but I'm guessing that should be good enough?

**Comment by amaurym** [comment]
Sure. Feel free to create a PR then, thanks!
