### ISSUE TITLE
Application error after new deployment on Heroku

### ISSUE THREAD

**Issue by ashokque** [reacherhq/check-if-email-exists#984]
I deployed app on Heroku but after installation, I received Application error message, while accessing it on the URL along with following message

_An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail_

I would appreciate any help.

Thank you.

**Comment by amaurym** [comment]
Related to https://github.com/reacherhq/backend/issues/195. Closing.
