### ISSUE TITLE
Docker post request issue

### ISSUE THREAD

**Issue by sricoolboy123** [reacherhq/check-if-email-exists#987]
Request bo
![issue](https://user-images.githubusercontent.com/90993553/136873749-e2281b40-a0b1-47cb-a674-b7c316891dac.PNG)
dy deserialize error: EOF while parsing a value at line 1 column 0

When I open the url directly it says: **HTTP method not allowed**

**Comment by amaurym** [comment]
Hey! Did you add anything in the body? You should add `to_email` in the body (see the "Body" tab on Postman)
